name: Publish release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GAVFU_PAT }}

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build for production
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: generate

      - name: Deploy to namek-network/dcf-home-deploy
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GAVFU_PAT }}
          SRC_FOLDER: dist
          DEST_OWNER: namek-network
          DEST_REPO: dcf-home-deploy
          DEST_BRANCH: main
          DEST_FOLDER: docs
