name: main-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn generate

      - name: Build and push docker
        run: |
          docker build -t coderyashiro/dcf-home:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push coderyashiro/dcf-home:latest
      - name: Upgrade home web
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull coderyashiro/dcf-home:latest
            cd /usr/local/docker/dcf-home
            docker-compose up -d 
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}